// Code generated by "stringer -type Month salary_sheet.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Shrawan-1]
	_ = x[Bhadra-2]
	_ = x[Ashoj-3]
	_ = x[Karthik-4]
	_ = x[Manghsir-5]
	_ = x[Poush-6]
	_ = x[Magh-7]
	_ = x[Falgun-8]
	_ = x[Chaitra-9]
	_ = x[Baisakh-10]
	_ = x[Jyestha-11]
	_ = x[Ashad-12]
}

const _Month_name = "ShrawanBhadraAshojKarthikManghsirPoushMaghFalgunChaitraBaisakhJyesthaAshad"

var _Month_index = [...]uint8{0, 7, 13, 18, 25, 33, 38, 42, 48, 55, 62, 69, 74}

func (i Month) String() string {
	i -= 1
	if i < 0 || i >= Month(len(_Month_index)-1) {
		return "Month(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Month_name[_Month_index[i]:_Month_index[i+1]]
}
