// Code generated by "stringer -type PaidStatus payment.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Complete-1]
	_ = x[Pending-2]
}

const _PaidStatus_name = "CompletePending"

var _PaidStatus_index = [...]uint8{0, 8, 15}

func (i PaidStatus) String() string {
	i -= 1
	if i < 0 || i >= PaidStatus(len(_PaidStatus_index)-1) {
		return "PaidStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PaidStatus_name[_PaidStatus_index[i]:_PaidStatus_index[i+1]]
}
