// Code generated by "stringer -type PaidMedium models/salary_payment.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Cash-1]
	_ = x[Bank-2]
	_ = x[Online-3]
}

const _PaidMedium_name = "CashBankOnline"

var _PaidMedium_index = [...]uint8{0, 4, 8, 14}

func (i PaidMedium) String() string {
	i -= 1
	if i < 0 || i >= PaidMedium(len(_PaidMedium_index)-1) {
		return "PaidMedium(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PaidMedium_name[_PaidMedium_index[i]:_PaidMedium_index[i+1]]
}
