version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT}:2345
    volumes:
      - .:/magazine_api
    env_file: .env
    container_name: magazine-web
    security_opt:
      - seccomp:unconfined
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    container_name: magazine-db
    ports:
      - 54323:${DB_PORT}
    volumes:
      - magazine_db:/var/lib/postgresql/data

  adminer:
    image: dockette/adminer:dg
    environment:
      - "MEMORY=512M"
    ports:
      - ${ADMINER_PORT}:80
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    restart: unless-stopped

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
        - ${SWAGGER_PORT}:8080
    volumes:
        - ./docs:/usr/share/nginx/html/docs
    environment:
        API_URL: docs/swagger.yaml

volumes:
  magazine_db:
  pgadmin: